---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
population = scan(text = "2.1	2.4	5.9	2.8	2.9	6.4
                  3.4	1.4	1.9	2.2	5.0	3.3
                  3.3	2.9	2.1	6.6	3.5	1.0
                  3.9	2.1	1.6	2.4	1.6	1.9
                  2.0	1.2	4.1	2.9	1.5	5.1
                  3.4	2.3	4.3	4.2	4.1	3.8")

sample(population, 6, replace = FALSE)
```

You can add options to executable code like this

```{r}
mysample = scan(text = "2.2 1.2 1.9 5.0 1.6 6.4")
res = NULL
#set.seed(123)
for(i in 1:200){
  student_sample = sample(population, 6, replace = TRUE)
  res[i] = mean(student_sample)
}

```

```{r}
ci = quantile(res, c(0.025, 0.975))
ci
```

```{r}
true_value = 3.1
true_value > ci[1] & true_value < ci[2]
```

```{r}
library(tidyverse)
speed_file = read_csv("https://raw.githubusercontent.com/DATA2002/data/master/speed_of_light.txt")
speed = speed_file$Speed_of_Light
p2 = ggplot(speed_file, aes(x="", y = Speed_of_Light)) + 
  geom_boxplot(colour = "red", outlier.size = 2) + 
  theme_classic(base_size = 16) + 
  labs(x = "", y = "Speed") + coord_flip()
```

```{r}
set.seed(123)
light_res = NULL
light_sample = sample(speed, 66, replace = TRUE)

light_sample
```

```{r}

light_df = data.frame(light_sample)
p1 = ggplot(light_df, aes(x="", y = light_sample)) + 
  geom_boxplot(colour = "red", outlier.size = 2) + 
  theme_classic(base_size = 16) + 
  labs(x = "", y = "Speed") + coord_flip()
```

```{r}
p1
p2
```

```{r}
B = 20
speedbmean = numeric(B)
for (i in 1:B){
  resampled_data = sample(speed, replace = TRUE)
  speedbmean[i] = mean(resampled_data)
}
speedbmean[1:10]
```

```{r}
hist(speedbmean)
abline(v = mean(speed), col = "red", lwd = 1)
```
